# Generated by Django 5.2.11 on 2026-02-18 21:35

from django.db import migrations

DEFAULT_CATEGORIES = [
    ('Beans', 'beans'),
    ('Breakfast', 'breakfast'),
    ('Chicken', 'chicken'),
    ('Dessert', 'dessert'),
    ('Dinner', 'dinner'),
    ('Fish', 'fish'),
    ('Lunch', 'lunch'),
    ('Meat', 'meat'),
    ('Pasta', 'pasta'),
    ('Snack', 'snack'),
]


def seed_categories(apps, schema_editor):
    Category = apps.get_model('recipes', 'Category')
    for name, slug in DEFAULT_CATEGORIES:
        Category.objects.get_or_create(slug=slug, defaults={'name': name})


def unseed_categories(apps, schema_editor):
    Category = apps.get_model('recipes', 'Category')
    slugs = [slug for _, slug in DEFAULT_CATEGORIES]
    Category.objects.filter(slug__in=slugs).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_category_remove_recipe_category_recipe_categories'),
    ]

    operations = [
        migrations.RunPython(seed_categories, unseed_categories),
    ]
