# Generated by Django 5.2.11 on 2026-02-18 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_seed_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='public',
            field=models.BooleanField(default=False, help_text='Make this recipe visible to all users.'),
        ),
    ]
