# Generated by Django 5.2.11 on 2026-02-18 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipe_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Recipe rating (1-5 stars).', null=True),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='aisle',
            field=models.CharField(blank=True, default='', help_text='Supermarket aisle (e.g. Produce, Dairy).', max_length=100),
        ),
    ]
