# Generated by Django 5.2.11 on 2026-02-19 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_category_user_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='quantity_unit',
            field=models.CharField(blank=True, choices=[('grams', 'grams'), ('kilograms', 'kilograms'), ('cups', 'cups'), ('tsp', 'tsp'), ('tbsp', 'tbsp'), ('piece', 'piece')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='quantity_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
