# Generated by Django 5.2.11 on 2026-02-19 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_migrate_ingredient_quantities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='quantity_unit',
            field=models.CharField(blank=True, choices=[('', '-- Unit --'), ('grams', 'grams'), ('kilograms', 'kilograms'), ('cups', 'cups'), ('tsp', 'tsp'), ('tbsp', 'tbsp'), ('piece', 'piece')], default='', max_length=20),
        ),
    ]
